// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateSandboxData, CreateSandboxErrors, CreateSandboxResponses, CreateTemplateData, CreateTemplateErrors, CreateTemplateResponses, CreateViewerData, CreateViewerErrors, CreateViewerResponses, DeleteSandboxData, DeleteSandboxErrors, DeleteSandboxResponses, DeleteSnapshotData, DeleteSnapshotErrors, DeleteSnapshotResponses, DeleteTemplateData, DeleteTemplateErrors, DeleteTemplateResponses, DeleteViewerData, DeleteViewerErrors, DeleteViewerResponses, EventsData, EventsErrors, EventsResponses, ExecData, ExecErrors, ExecResponses, ForkData, ForkErrors, ForkResponses, GetSandboxData, GetSandboxErrors, GetSandboxResponses, GetSnapshotData, GetSnapshotErrors, GetSnapshotResponses, GetTemplateData, GetTemplateErrors, GetTemplateResponses, HealthData, HealthErrors, HealthResponses, ListSandboxesData, ListSandboxesErrors, ListSandboxesResponses, ListSnapshotsData, ListSnapshotsErrors, ListSnapshotsResponses, ListTemplatesData, ListTemplatesErrors, ListTemplatesResponses, ListViewersData, ListViewersErrors, ListViewersResponses, PublishData, PublishErrors, PublishResponses, ReadFileData, ReadFileErrors, ReadFileResponses, RestoreData, RestoreErrors, RestoreResponses, RetireData, RetireErrors, RetireResponses, SnapshotData, SnapshotErrors, SnapshotResponses, WriteFileData, WriteFileErrors, WriteFileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read the event stream of this tenant.
 */
export const events = <ThrowOnError extends boolean = false>(options?: Options<EventsData, ThrowOnError>) => (options?.client ?? client).get<EventsResponses, EventsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/events',
    ...options
});

/**
 * Report whether the host can run sandboxes.
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => (options?.client ?? client).get<HealthResponses, HealthErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/health',
    ...options
});

/**
 * List the sandboxes of this tenant.
 */
export const listSandboxes = <ThrowOnError extends boolean = false>(options?: Options<ListSandboxesData, ThrowOnError>) => (options?.client ?? client).get<ListSandboxesResponses, ListSandboxesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/sandboxes',
    ...options
});

/**
 * Create a sandbox by restoring a template snapshot.
 */
export const createSandbox = <ThrowOnError extends boolean = false>(options: Options<CreateSandboxData, ThrowOnError>) => (options.client ?? client).post<CreateSandboxResponses, CreateSandboxErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/sandboxes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Destroy a sandbox and retire its hostnames.
 */
export const deleteSandbox = <ThrowOnError extends boolean = false>(options: Options<DeleteSandboxData, ThrowOnError>) => (options.client ?? client).delete<DeleteSandboxResponses, DeleteSandboxErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/sandboxes/{id}',
    ...options
});

/**
 * Read one sandbox with its published ports.
 */
export const getSandbox = <ThrowOnError extends boolean = false>(options: Options<GetSandboxData, ThrowOnError>) => (options.client ?? client).get<GetSandboxResponses, GetSandboxErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/sandboxes/{id}',
    ...options
});

/**
 * Run a command inside a sandbox. Accept text/event-stream to read the output as it runs.
 */
export const exec = <ThrowOnError extends boolean = false>(options: Options<ExecData, ThrowOnError>) => (options.client ?? client).post<ExecResponses, ExecErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/sandboxes/{id}/exec',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read one file out of a sandbox.
 */
export const readFile = <ThrowOnError extends boolean = false>(options: Options<ReadFileData, ThrowOnError>) => (options.client ?? client).get<ReadFileResponses, ReadFileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/sandboxes/{id}/files/{path}',
    ...options
});

/**
 * Write one file into a sandbox.
 */
export const writeFile = <ThrowOnError extends boolean = false>(options: Options<WriteFileData, ThrowOnError>) => (options.client ?? client).put<WriteFileResponses, WriteFileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/sandboxes/{id}/files/{path}',
    ...options
});

/**
 * Snapshot a running sandbox and restore several copies of it.
 */
export const fork = <ThrowOnError extends boolean = false>(options: Options<ForkData, ThrowOnError>) => (options.client ?? client).post<ForkResponses, ForkErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/sandboxes/{id}/fork',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Serve a guest port on a public hostname.
 */
export const publish = <ThrowOnError extends boolean = false>(options: Options<PublishData, ThrowOnError>) => (options.client ?? client).post<PublishResponses, PublishErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/sandboxes/{id}/publish',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retire a published hostname. It answers 404 from then on.
 */
export const retire = <ThrowOnError extends boolean = false>(options: Options<RetireData, ThrowOnError>) => (options.client ?? client).delete<RetireResponses, RetireErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/sandboxes/{id}/publish/{port}',
    ...options
});

/**
 * Snapshot a sandbox. With stop the sandbox sleeps and keeps its hostnames.
 */
export const snapshot = <ThrowOnError extends boolean = false>(options: Options<SnapshotData, ThrowOnError>) => (options.client ?? client).post<SnapshotResponses, SnapshotErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/sandboxes/{id}/snapshot',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List the snapshots of this tenant.
 */
export const listSnapshots = <ThrowOnError extends boolean = false>(options?: Options<ListSnapshotsData, ThrowOnError>) => (options?.client ?? client).get<ListSnapshotsResponses, ListSnapshotsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/snapshots',
    ...options
});

/**
 * Delete a snapshot that has no live sandbox.
 */
export const deleteSnapshot = <ThrowOnError extends boolean = false>(options: Options<DeleteSnapshotData, ThrowOnError>) => (options.client ?? client).delete<DeleteSnapshotResponses, DeleteSnapshotErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/snapshots/{id}',
    ...options
});

/**
 * Read one snapshot.
 */
export const getSnapshot = <ThrowOnError extends boolean = false>(options: Options<GetSnapshotData, ThrowOnError>) => (options.client ?? client).get<GetSnapshotResponses, GetSnapshotErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/snapshots/{id}',
    ...options
});

/**
 * Restore a snapshot into one or more new sandboxes.
 */
export const restore = <ThrowOnError extends boolean = false>(options: Options<RestoreData, ThrowOnError>) => (options.client ?? client).post<RestoreResponses, RestoreErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/snapshots/{id}/restore',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List the templates of this tenant.
 */
export const listTemplates = <ThrowOnError extends boolean = false>(options?: Options<ListTemplatesData, ThrowOnError>) => (options?.client ?? client).get<ListTemplatesResponses, ListTemplatesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/templates',
    ...options
});

/**
 * Build a template from an OCI image. The build runs after the answer.
 */
export const createTemplate = <ThrowOnError extends boolean = false>(options: Options<CreateTemplateData, ThrowOnError>) => (options.client ?? client).post<CreateTemplateResponses, CreateTemplateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/templates',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a template that has no live sandbox and no snapshot.
 */
export const deleteTemplate = <ThrowOnError extends boolean = false>(options: Options<DeleteTemplateData, ThrowOnError>) => (options.client ?? client).delete<DeleteTemplateResponses, DeleteTemplateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/templates/{name}',
    ...options
});

/**
 * Read one template.
 */
export const getTemplate = <ThrowOnError extends boolean = false>(options: Options<GetTemplateData, ThrowOnError>) => (options.client ?? client).get<GetTemplateResponses, GetTemplateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/templates/{name}',
    ...options
});

/**
 * List the viewers of this tenant.
 */
export const listViewers = <ThrowOnError extends boolean = false>(options?: Options<ListViewersData, ThrowOnError>) => (options?.client ?? client).get<ListViewersResponses, ListViewersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/viewers',
    ...options
});

/**
 * Add a viewer of this tenant. A viewer opens team previews and nothing else.
 */
export const createViewer = <ThrowOnError extends boolean = false>(options: Options<CreateViewerData, ThrowOnError>) => (options.client ?? client).post<CreateViewerResponses, CreateViewerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/viewers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke one viewer. The viewer is disabled and its sessions end.
 */
export const deleteViewer = <ThrowOnError extends boolean = false>(options: Options<DeleteViewerData, ThrowOnError>) => (options.client ?? client).delete<DeleteViewerResponses, DeleteViewerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, { scheme: 'bearer', type: 'http' }],
    url: '/v1/viewers/{id}',
    ...options
});
