// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.example.com' | (string & {});
};

export type Error = {
    error?: {
        code?: string;
        message?: string;
    };
};

export type Event = {
    at?: string;
    from?: string;
    id?: number;
    reason?: string;
    sandbox_id?: string;
    to?: string;
};

export type EventList = Array<Event>;

export type ExecResult = {
    exit_code?: number;
    stderr?: string;
    stdout?: string;
    timed_out?: boolean;
    truncated?: boolean;
};

export type FileBody = Blob | File;

export type Health = {
    firecracker?: string;
    kvm?: boolean;
    ok?: boolean;
    sandboxes?: number;
};

export type Published = {
    port?: number;
    url?: string;
    visibility?: string;
};

export type Registry = {
    created_at?: string;
    host?: string;
    username?: string;
};

export type RegistryList = Array<Registry>;

export type Sandbox = {
    created_at?: string;
    env_keys?: Array<string>;
    id?: string;
    lifecycle?: string;
    metadata?: {
        [key: string]: unknown;
    };
    published?: Array<Published>;
    state?: string;
    template?: string;
};

export type SandboxList = Array<Sandbox>;

export type Snapshot = {
    created_at?: string;
    id?: string;
    size_bytes?: number;
    template?: string;
};

export type SnapshotCreated = {
    snapshot_id?: string;
};

export type SnapshotList = Array<Snapshot>;

export type Template = {
    created_at?: string;
    disk_mb?: number;
    egress_allow?: Array<string>;
    error?: string;
    image?: string;
    image_digest?: string;
    memory_mb?: number;
    name?: string;
    port?: number;
    sandboxes?: number;
    snapshot_bytes?: number;
    start?: Array<string>;
    state?: string;
    ttl_seconds?: number;
    vcpus?: number;
};

export type TemplateList = Array<Template>;

export type TemplateState = {
    name?: string;
    state?: string;
};

export type Tenant = {
    id?: string;
    max_sandboxes?: number;
    max_snapshot_bytes?: number;
    max_templates?: number;
    name?: string;
    sandboxes?: number;
    snapshot_bytes?: number;
    templates?: number;
};

export type TenantList = Array<Tenant>;

export type Viewer = {
    created_at?: string;
    email?: string;
    id?: string;
    tenant?: string;
};

export type ViewerList = Array<Viewer>;

export type EventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/events';
};

export type EventsErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type EventsError = EventsErrors[keyof EventsErrors];

export type EventsResponses = {
    /**
     * The call succeeded.
     */
    200: EventList;
};

export type EventsResponse = EventsResponses[keyof EventsResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/health';
};

export type HealthErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type HealthError = HealthErrors[keyof HealthErrors];

export type HealthResponses = {
    /**
     * The call succeeded.
     */
    200: Health;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type ListRegistriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/registries';
};

export type ListRegistriesErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type ListRegistriesError = ListRegistriesErrors[keyof ListRegistriesErrors];

export type ListRegistriesResponses = {
    /**
     * The call succeeded.
     */
    200: RegistryList;
};

export type ListRegistriesResponse = ListRegistriesResponses[keyof ListRegistriesResponses];

export type PutRegistryData = {
    body: {
        host: string;
        token: string;
        username: string;
    };
    path?: never;
    query?: never;
    url: '/v1/registries';
};

export type PutRegistryErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type PutRegistryError = PutRegistryErrors[keyof PutRegistryErrors];

export type PutRegistryResponses = {
    /**
     * The call succeeded.
     */
    201: Registry;
};

export type PutRegistryResponse = PutRegistryResponses[keyof PutRegistryResponses];

export type DeleteRegistryData = {
    body?: never;
    path: {
        /**
         * Registry hostname.
         */
        host: string;
    };
    query?: never;
    url: '/v1/registries/{host}';
};

export type DeleteRegistryErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type DeleteRegistryError = DeleteRegistryErrors[keyof DeleteRegistryErrors];

export type DeleteRegistryResponses = {
    /**
     * The call succeeded.
     */
    204: void;
};

export type DeleteRegistryResponse = DeleteRegistryResponses[keyof DeleteRegistryResponses];

export type ListSandboxesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/sandboxes';
};

export type ListSandboxesErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type ListSandboxesError = ListSandboxesErrors[keyof ListSandboxesErrors];

export type ListSandboxesResponses = {
    /**
     * The call succeeded.
     */
    200: SandboxList;
};

export type ListSandboxesResponse = ListSandboxesResponses[keyof ListSandboxesResponses];

export type CreateSandboxData = {
    body: {
        env?: {
            [key: string]: unknown;
        };
        idle_seconds?: number;
        lifecycle?: string;
        metadata?: {
            [key: string]: unknown;
        };
        secrets?: Array<string>;
        template: string;
        ttl_seconds?: number;
    };
    path?: never;
    query?: never;
    url: '/v1/sandboxes';
};

export type CreateSandboxErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type CreateSandboxError = CreateSandboxErrors[keyof CreateSandboxErrors];

export type CreateSandboxResponses = {
    /**
     * The call succeeded.
     */
    201: Sandbox;
};

export type CreateSandboxResponse = CreateSandboxResponses[keyof CreateSandboxResponses];

export type DeleteSandboxData = {
    body?: never;
    path: {
        /**
         * Sandbox id.
         */
        id: string;
    };
    query?: never;
    url: '/v1/sandboxes/{id}';
};

export type DeleteSandboxErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type DeleteSandboxError = DeleteSandboxErrors[keyof DeleteSandboxErrors];

export type DeleteSandboxResponses = {
    /**
     * The call succeeded.
     */
    204: void;
};

export type DeleteSandboxResponse = DeleteSandboxResponses[keyof DeleteSandboxResponses];

export type GetSandboxData = {
    body?: never;
    path: {
        /**
         * Sandbox id.
         */
        id: string;
    };
    query?: never;
    url: '/v1/sandboxes/{id}';
};

export type GetSandboxErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type GetSandboxError = GetSandboxErrors[keyof GetSandboxErrors];

export type GetSandboxResponses = {
    /**
     * The call succeeded.
     */
    200: Sandbox;
};

export type GetSandboxResponse = GetSandboxResponses[keyof GetSandboxResponses];

export type ExecData = {
    body: {
        cmd: Array<string>;
        cwd?: string;
        env?: {
            [key: string]: unknown;
        };
        timeout_seconds?: number;
    };
    path: {
        /**
         * Sandbox id.
         */
        id: string;
    };
    query?: never;
    url: '/v1/sandboxes/{id}/exec';
};

export type ExecErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type ExecError = ExecErrors[keyof ExecErrors];

export type ExecResponses = {
    /**
     * The call succeeded.
     */
    200: ExecResult;
};

export type ExecResponse = ExecResponses[keyof ExecResponses];

export type ReadFileData = {
    body?: never;
    path: {
        /**
         * Sandbox id.
         */
        id: string;
        /**
         * Path inside the sandbox.
         */
        path: string;
    };
    query?: never;
    url: '/v1/sandboxes/{id}/files/{path}';
};

export type ReadFileErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type ReadFileError = ReadFileErrors[keyof ReadFileErrors];

export type ReadFileResponses = {
    /**
     * The call succeeded.
     */
    200: FileBody;
};

export type ReadFileResponse = ReadFileResponses[keyof ReadFileResponses];

export type WriteFileData = {
    body?: never;
    path: {
        /**
         * Sandbox id.
         */
        id: string;
        /**
         * Path inside the sandbox.
         */
        path: string;
    };
    query?: never;
    url: '/v1/sandboxes/{id}/files/{path}';
};

export type WriteFileErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type WriteFileError = WriteFileErrors[keyof WriteFileErrors];

export type WriteFileResponses = {
    /**
     * The call succeeded.
     */
    204: void;
};

export type WriteFileResponse = WriteFileResponses[keyof WriteFileResponses];

export type ForkData = {
    body: {
        allow_secret_fork?: boolean;
        count: number;
    };
    path: {
        /**
         * Sandbox id.
         */
        id: string;
    };
    query?: never;
    url: '/v1/sandboxes/{id}/fork';
};

export type ForkErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type ForkError = ForkErrors[keyof ForkErrors];

export type ForkResponses = {
    /**
     * The call succeeded.
     */
    201: SandboxList;
};

export type ForkResponse = ForkResponses[keyof ForkResponses];

export type PublishData = {
    body: {
        port: number;
        visibility: string;
    };
    path: {
        /**
         * Sandbox id.
         */
        id: string;
    };
    query?: never;
    url: '/v1/sandboxes/{id}/publish';
};

export type PublishErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type PublishError = PublishErrors[keyof PublishErrors];

export type PublishResponses = {
    /**
     * The call succeeded.
     */
    201: Published;
};

export type PublishResponse = PublishResponses[keyof PublishResponses];

export type RetireData = {
    body?: never;
    path: {
        /**
         * Sandbox id.
         */
        id: string;
        /**
         * Published guest port.
         */
        port: number;
    };
    query?: never;
    url: '/v1/sandboxes/{id}/publish/{port}';
};

export type RetireErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type RetireError = RetireErrors[keyof RetireErrors];

export type RetireResponses = {
    /**
     * The call succeeded.
     */
    204: void;
};

export type RetireResponse = RetireResponses[keyof RetireResponses];

export type SnapshotData = {
    body: {
        stop?: boolean;
    };
    path: {
        /**
         * Sandbox id.
         */
        id: string;
    };
    query?: never;
    url: '/v1/sandboxes/{id}/snapshot';
};

export type SnapshotErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type SnapshotError = SnapshotErrors[keyof SnapshotErrors];

export type SnapshotResponses = {
    /**
     * The call succeeded.
     */
    201: SnapshotCreated;
};

export type SnapshotResponse = SnapshotResponses[keyof SnapshotResponses];

export type ListSnapshotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/snapshots';
};

export type ListSnapshotsErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type ListSnapshotsError = ListSnapshotsErrors[keyof ListSnapshotsErrors];

export type ListSnapshotsResponses = {
    /**
     * The call succeeded.
     */
    200: SnapshotList;
};

export type ListSnapshotsResponse = ListSnapshotsResponses[keyof ListSnapshotsResponses];

export type DeleteSnapshotData = {
    body?: never;
    path: {
        /**
         * Snapshot id.
         */
        id: string;
    };
    query?: never;
    url: '/v1/snapshots/{id}';
};

export type DeleteSnapshotErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type DeleteSnapshotError = DeleteSnapshotErrors[keyof DeleteSnapshotErrors];

export type DeleteSnapshotResponses = {
    /**
     * The call succeeded.
     */
    204: void;
};

export type DeleteSnapshotResponse = DeleteSnapshotResponses[keyof DeleteSnapshotResponses];

export type GetSnapshotData = {
    body?: never;
    path: {
        /**
         * Snapshot id.
         */
        id: string;
    };
    query?: never;
    url: '/v1/snapshots/{id}';
};

export type GetSnapshotErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type GetSnapshotError = GetSnapshotErrors[keyof GetSnapshotErrors];

export type GetSnapshotResponses = {
    /**
     * The call succeeded.
     */
    200: Snapshot;
};

export type GetSnapshotResponse = GetSnapshotResponses[keyof GetSnapshotResponses];

export type RestoreData = {
    body: {
        allow_secret_fork?: boolean;
        count: number;
    };
    path: {
        /**
         * Snapshot id.
         */
        id: string;
    };
    query?: never;
    url: '/v1/snapshots/{id}/restore';
};

export type RestoreErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type RestoreError = RestoreErrors[keyof RestoreErrors];

export type RestoreResponses = {
    /**
     * The call succeeded.
     */
    201: SandboxList;
};

export type RestoreResponse = RestoreResponses[keyof RestoreResponses];

export type ListTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/templates';
};

export type ListTemplatesErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type ListTemplatesError = ListTemplatesErrors[keyof ListTemplatesErrors];

export type ListTemplatesResponses = {
    /**
     * The call succeeded.
     */
    200: TemplateList;
};

export type ListTemplatesResponse = ListTemplatesResponses[keyof ListTemplatesResponses];

export type CreateTemplateData = {
    body: {
        disk_mb?: number;
        egress_allow: Array<string>;
        image: string;
        memory_mb?: number;
        name: string;
        port?: number;
        setup?: Array<string>;
        start?: Array<string>;
        ttl_seconds?: number;
        vcpus?: number;
    };
    path?: never;
    query?: never;
    url: '/v1/templates';
};

export type CreateTemplateErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type CreateTemplateError = CreateTemplateErrors[keyof CreateTemplateErrors];

export type CreateTemplateResponses = {
    /**
     * The call succeeded.
     */
    202: TemplateState;
};

export type CreateTemplateResponse = CreateTemplateResponses[keyof CreateTemplateResponses];

export type DeleteTemplateData = {
    body?: never;
    path: {
        /**
         * Name of the template.
         */
        name: string;
    };
    query?: never;
    url: '/v1/templates/{name}';
};

export type DeleteTemplateErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type DeleteTemplateError = DeleteTemplateErrors[keyof DeleteTemplateErrors];

export type DeleteTemplateResponses = {
    /**
     * The call succeeded.
     */
    204: void;
};

export type DeleteTemplateResponse = DeleteTemplateResponses[keyof DeleteTemplateResponses];

export type GetTemplateData = {
    body?: never;
    path: {
        /**
         * Name of the template.
         */
        name: string;
    };
    query?: never;
    url: '/v1/templates/{name}';
};

export type GetTemplateErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type GetTemplateError = GetTemplateErrors[keyof GetTemplateErrors];

export type GetTemplateResponses = {
    /**
     * The call succeeded.
     */
    200: Template;
};

export type GetTemplateResponse = GetTemplateResponses[keyof GetTemplateResponses];

export type ListViewersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/viewers';
};

export type ListViewersErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type ListViewersError = ListViewersErrors[keyof ListViewersErrors];

export type ListViewersResponses = {
    /**
     * The call succeeded.
     */
    200: ViewerList;
};

export type ListViewersResponse = ListViewersResponses[keyof ListViewersResponses];

export type CreateViewerData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/v1/viewers';
};

export type CreateViewerErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type CreateViewerError = CreateViewerErrors[keyof CreateViewerErrors];

export type CreateViewerResponses = {
    /**
     * The call succeeded.
     */
    201: Viewer;
};

export type CreateViewerResponse = CreateViewerResponses[keyof CreateViewerResponses];

export type DeleteViewerData = {
    body?: never;
    path: {
        /**
         * Viewer id.
         */
        id: string;
    };
    query?: never;
    url: '/v1/viewers/{id}';
};

export type DeleteViewerErrors = {
    /**
     * The request is invalid. The message names the field.
     */
    400: Error;
    /**
     * The credential is missing, expired or revoked.
     */
    401: Error;
    /**
     * The row does not exist, or it belongs to another tenant.
     */
    404: Error;
    /**
     * The call conflicts with the state, for example a template that still has sandboxes.
     */
    409: Error;
    /**
     * A cap of this tenant is reached. The message names the cap.
     */
    507: Error;
};

export type DeleteViewerError = DeleteViewerErrors[keyof DeleteViewerErrors];

export type DeleteViewerResponses = {
    /**
     * The call succeeded.
     */
    204: void;
};

export type DeleteViewerResponse = DeleteViewerResponses[keyof DeleteViewerResponses];
