// Code generated by scripts/gen-versions.sh from scripts/versions.env; DO NOT EDIT.

package main

const (
	arch               = "x86_64"
	firecrackerVersion = "v1.17.0"
	firecrackerURL     = "https://github.com/firecracker-microvm/firecracker/releases/download/v1.17.0/firecracker-v1.17.0-x86_64.tgz"
	firecrackerSHA256  = "06094a1108ae9e82aa4c23a775aa92758f53f1175d422270d9d6162cb9ade558"
	kernelVersion      = "6.1.186"
	kernelURL          = "https://s3.amazonaws.com/spec.ccfc.min/firecracker-ci/20260909-a8e1c3830545-0/x86_64/vmlinux-6.1.186"
	kernelSHA256       = "51565cd5d8bc6d7f3c856acdc8028ad1ef9996d581ac25f47a03429608c4f6ed"
)
