#!/usr/bin/env bash
# Generate the Go copy of the version pins. scripts/versions.env is the only
# version file; cmd/kiln/versions_gen.go is generated from it and checked by
# checks/versions.sh.
set -euo pipefail

here="${BASH_SOURCE[0]%/*}"
[ "$here" = "${BASH_SOURCE[0]}" ] && here="."
here="$(cd "$here" && pwd -P)"
# shellcheck source=versions.env
source "$here/versions.env"

for v in ARCH FIRECRACKER_VERSION FIRECRACKER_URL FIRECRACKER_SHA256 \
         KERNEL_VERSION KERNEL_URL KERNEL_SHA256; do
  eval "val=\${$v:-}"
  [ -n "$val" ] || { echo "gen-versions: versions.env does not set $v" >&2; exit 1; }
done

out="${1:-/dev/stdout}"
cat > "$out" <<EOF
// Code generated by scripts/gen-versions.sh from scripts/versions.env; DO NOT EDIT.

package main

const (
	arch               = "$ARCH"
	firecrackerVersion = "$FIRECRACKER_VERSION"
	firecrackerURL     = "$FIRECRACKER_URL"
	firecrackerSHA256  = "$FIRECRACKER_SHA256"
	kernelVersion      = "$KERNEL_VERSION"
	kernelURL          = "$KERNEL_URL"
	kernelSHA256       = "$KERNEL_SHA256"
)
EOF
